Modify provision.sh, Makefile and update README
edly-io/devstack pull request #9
Opened 2019-09-05 06:57 UTC by danialmalik

Update README:
    Update README according to Edly requirements.

Makefile:
    Change "requirements" rule to install php and composer

provision.sh:
    remove provision-wordpress.sh

provision-wordpress.sh:
    add "#!/bin/bash" at start of file.

2019-09-11 10:17 UTC, etechdevai approved these changes

2019-09-11 10:29 UTC, zubair-arbi requested changes

2019-09-11 10:29 UTC, zubair-arbi commented on README.rst
> +    virtualenv -p python venv
use python3

2019-09-11 10:29 UTC, zubair-arbi commented on README.rst
> +    chmod 0777 /var/www/html/wp-content -R
I believe we don't need this much open permissions. Try using following command:
```chown -R www-data:www-data wp-content```

2019-09-11 10:29 UTC, zubair-arbi commented on README.rst
> +2. Run ``sudo chmod -R 777 src/``
I don't think we need to set these permissions. Try setting up edly devstack without this step.

2019-09-11 10:29 UTC, zubair-arbi commented on README.rst
> +        "/edx/src/edly-edx-themes"
Remove this. With the change I made https://github.com/edly-io/devstack/pull/7, `st-lutherx` is automatically shared in the `/edx/app/edxapp/edx-platform/themes`. So remove this line.

2019-09-11 10:29 UTC, zubair-arbi commented on README.rst
> +    ./provision-wordpress.sh
Also add steps to import `wordpress dump`, acf fields etc.

2019-09-24 07:18 UTC, imhassantariq commented on README.rst
> +    apt-get install php7.2
This container already contains php7.3 in it so we don't need it to install.

2019-09-24 07:18 UTC, imhassantariq commented on README.rst
> +    ./provision-wordpress.sh
While provision we face several issues:
 - Permission denied Exception for theme and plugin folder this command outside helped:
`sudo chmod a+rw ../edly-wp-plugin -R`
`sudo chmod a+rw ../edly-wp-theme -R`

- Another issue is php7.2-xml is not install on my host machine so we installed it on our own using this command:
`sudo apt-get install php7.2-xml`

@tehreem-sadat Faced the same issues.

2019-09-26 07:29 UTC, zubair-arbi approved these changes
Thanks for updating the setup guide 👍

2019-09-26 09:02 UTC, merged